create extension if not exists pgcrypto;

-- GlobeChat v2 uses anonymous Supabase Auth so usernames/groups can be secured per user.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[A-Za-z0-9_]{3,24}$'),
  created_at timestamptz not null default now()
);

create table if not exists public.chat_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) between 1 and 60),
  owner_id uuid not null references auth.users(id) on delete cascade,
  passcode_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  group_id uuid references public.chat_groups(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  active boolean not null default true,
  primary key(group_id,user_id)
);

create table if not exists public.messages_v2 (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  content text not null default '' check (char_length(content) <= 500),
  chat_id uuid references public.chat_groups(id) on delete cascade,
  is_global boolean not null default false,
  created_at timestamptz not null default now(),
  check ((is_global and chat_id is null) or ((not is_global) and chat_id is not null))
);

create table if not exists public.attachments (
  id uuid primary key default gen_random_uuid(),
  message_id bigint not null references public.messages_v2(id) on delete cascade,
  storage_path text not null,
  file_name text not null,
  mime_type text not null,
  size_bytes bigint not null check(size_bytes between 1 and 10485760),
  created_at timestamptz not null default now()
);

create table if not exists public.group_access_attempts (
  group_id uuid references public.chat_groups(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  window_started_at timestamptz not null default now(),
  attempts int not null default 0,
  primary key(group_id,user_id)
);

create index if not exists msg_global_time on public.messages_v2(created_at desc) where is_global;
create index if not exists msg_group_time on public.messages_v2(chat_id,created_at desc);
create index if not exists msg_search on public.messages_v2 using gin(to_tsvector('simple',content));

create or replace function public.claim_username(p_username text)
returns text language plpgsql security definer set search_path=public as $$
declare u text:=trim(p_username);
begin
 if auth.uid() is null then raise exception 'Not signed in'; end if;
 if u !~ '^[A-Za-z0-9_]{3,24}$' then raise exception 'Use 3-24 letters, numbers, or underscores'; end if;
 if exists(select 1 from profiles where id=auth.uid()) then
   select username into u from profiles where id=auth.uid();
   return u; -- immutable after first claim
 end if;
 insert into profiles(id,username) values(auth.uid(),u);
 return u;
exception when unique_violation then raise exception 'That username is already taken';
end $$;

create or replace function public.create_private_group(p_name text,p_passcode text)
returns uuid language plpgsql security definer set search_path=public as $$
declare gid uuid;
begin
 if auth.uid() is null then raise exception 'Not signed in'; end if;
 if char_length(trim(p_name)) not between 1 and 60 then raise exception 'Invalid group name'; end if;
 if p_passcode !~ '^[0-9]{6}$' then raise exception 'Passcode must be exactly 6 digits'; end if;
 insert into chat_groups(name,owner_id,passcode_hash)
 values(trim(p_name),auth.uid(),crypt(p_passcode,gen_salt('bf'))) returning id into gid;
 insert into group_members(group_id,user_id,joined_at,active) values(gid,auth.uid(),now(),true);
 return gid;
end $$;

create or replace function public.join_private_group(p_group_id uuid,p_passcode text)
returns boolean language plpgsql security definer set search_path=public as $$
declare h text; a group_access_attempts%rowtype;
begin
 if auth.uid() is null then raise exception 'Not signed in'; end if;
 if exists(select 1 from group_members where group_id=p_group_id and user_id=auth.uid()) then return true; end if;
 select passcode_hash into h from chat_groups where id=p_group_id;
 if h is null then raise exception 'Group not found'; end if;

 insert into group_access_attempts(group_id,user_id) values(p_group_id,auth.uid())
 on conflict do nothing;
 select * into a from group_access_attempts where group_id=p_group_id and user_id=auth.uid() for update;

 if a.window_started_at < now()-interval '24 hours' then
   update group_access_attempts set attempts=0,window_started_at=now()
   where group_id=p_group_id and user_id=auth.uid();
   a.attempts:=0;
 end if;
 if a.attempts>=5 then raise exception 'Five attempts used. Try again after the 24-hour window resets.'; end if;

 if crypt(p_passcode,h)<>h then
   update group_access_attempts set attempts=attempts+1 where group_id=p_group_id and user_id=auth.uid();
   raise exception 'Incorrect passcode';
 end if;

 insert into group_members(group_id,user_id) values(p_group_id,auth.uid()) on conflict do nothing;
 return true;
end $$;

create or replace function public.delete_private_group(p_group_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 delete from chat_groups where id=p_group_id and owner_id=auth.uid();
 if not found then raise exception 'Only the group owner can delete this group'; end if;
 return true;
end $$;

alter table profiles enable row level security;
alter table chat_groups enable row level security;
alter table group_members enable row level security;
alter table messages_v2 enable row level security;
alter table attachments enable row level security;
alter table group_access_attempts enable row level security;

drop policy if exists p_profiles_read on profiles;
create policy p_profiles_read on profiles for select to authenticated using(true);

drop policy if exists p_groups_read on chat_groups;
create policy p_groups_read on chat_groups for select to authenticated using(true);

drop policy if exists p_members_read on group_members;
create policy p_members_read on group_members for select to authenticated using(user_id=auth.uid());

drop policy if exists p_msg_read on messages_v2;
create policy p_msg_read on messages_v2 for select to authenticated using(
 is_global or exists(select 1 from group_members gm where gm.group_id=messages_v2.chat_id and gm.user_id=auth.uid())
);

drop policy if exists p_msg_write on messages_v2;
create policy p_msg_write on messages_v2 for insert to authenticated with check(
 sender_id=auth.uid() and (
   (is_global and chat_id is null) or
   ((not is_global) and exists(select 1 from group_members gm where gm.group_id=messages_v2.chat_id and gm.user_id=auth.uid()))
 )
);

drop policy if exists p_attach_read on attachments;
create policy p_attach_read on attachments for select to authenticated using(
 exists(select 1 from messages_v2 m where m.id=attachments.message_id and
 (m.is_global or exists(select 1 from group_members gm where gm.group_id=m.chat_id and gm.user_id=auth.uid())))
);
drop policy if exists p_attach_write on attachments;
create policy p_attach_write on attachments for insert to authenticated with check(
 exists(select 1 from messages_v2 m where m.id=attachments.message_id and m.sender_id=auth.uid())
);

grant execute on function claim_username(text) to authenticated;
grant execute on function create_private_group(text,text) to authenticated;
grant execute on function join_private_group(uuid,text) to authenticated;
grant execute on function delete_private_group(uuid) to authenticated;

-- Storage bucket + policies (10 MB max; private)
insert into storage.buckets(id,name,public,file_size_limit)
values('chat-files','chat-files',false,10485760)
on conflict(id) do update set public=false,file_size_limit=10485760;

drop policy if exists "chat files upload" on storage.objects;
create policy "chat files upload" on storage.objects for insert to authenticated
with check(bucket_id='chat-files' and (storage.foldername(name))[1]=auth.uid()::text);

drop policy if exists "chat files read" on storage.objects;
create policy "chat files read" on storage.objects for select to authenticated
using(bucket_id='chat-files');

do $$ begin
  alter publication supabase_realtime add table public.messages_v2;
exception when duplicate_object then null;
end $$;


create or replace function public.leave_private_group(p_group_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if exists(select 1 from chat_groups where id=p_group_id and owner_id=auth.uid()) then
   raise exception 'The owner cannot leave their own group. Delete the group instead.';
 end if;
 delete from group_members where group_id=p_group_id and user_id=auth.uid();
 return true;
end $$;

grant execute on function public.leave_private_group(uuid) to authenticated;

-- v2.3 active-membership functions/policies

-- GlobeChat v2.3 non-destructive group membership upgrade.
-- This migration does not delete tables, messages, groups, or membership rows.

alter table public.group_members
add column if not exists active boolean not null default true;

create or replace function public.leave_private_group(p_group_id uuid)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then raise exception 'Not signed in'; end if;

  if exists (
    select 1 from public.chat_groups
    where id=p_group_id and owner_id=auth.uid()
  ) then
    raise exception 'The owner cannot leave their own group. Delete the group instead.';
  end if;

  update public.group_members
  set active=false
  where group_id=p_group_id and user_id=auth.uid();

  return true;
end;
$$;

create or replace function public.join_private_group(p_group_id uuid,p_passcode text)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare h text;
declare a public.group_access_attempts%rowtype;
begin
  if auth.uid() is null then raise exception 'Not signed in'; end if;

  if exists (
    select 1 from public.group_members
    where group_id=p_group_id and user_id=auth.uid() and active=true
  ) then
    return true;
  end if;

  select passcode_hash into h
  from public.chat_groups
  where id=p_group_id;

  if h is null then raise exception 'Group not found'; end if;

  insert into public.group_access_attempts(group_id,user_id)
  values(p_group_id,auth.uid())
  on conflict do nothing;

  select * into a
  from public.group_access_attempts
  where group_id=p_group_id and user_id=auth.uid()
  for update;

  if a.window_started_at < now()-interval '24 hours' then
    update public.group_access_attempts
    set attempts=0,window_started_at=now()
    where group_id=p_group_id and user_id=auth.uid();
    a.attempts:=0;
  end if;

  if a.attempts>=5 then
    raise exception 'Five attempts used. Try again after the 24-hour window resets.';
  end if;

  if crypt(p_passcode,h)<>h then
    update public.group_access_attempts
    set attempts=attempts+1
    where group_id=p_group_id and user_id=auth.uid();
    raise exception 'Incorrect passcode';
  end if;

  insert into public.group_members(group_id,user_id,active)
  values(p_group_id,auth.uid(),true)
  on conflict(group_id,user_id)
  do update set active=true,joined_at=now();

  return true;
end;
$$;

drop policy if exists p_members_read on public.group_members;
create policy p_members_read on public.group_members
for select to authenticated
using(user_id=auth.uid());

drop policy if exists p_msg_read on public.messages_v2;
create policy p_msg_read on public.messages_v2
for select to authenticated
using(
  is_global
  or exists(
    select 1 from public.group_members gm
    where gm.group_id=messages_v2.chat_id
      and gm.user_id=auth.uid()
      and gm.active=true
  )
);

drop policy if exists p_msg_write on public.messages_v2;
create policy p_msg_write on public.messages_v2
for insert to authenticated
with check(
  sender_id=auth.uid()
  and (
    (is_global and chat_id is null)
    or (
      (not is_global)
      and exists(
        select 1 from public.group_members gm
        where gm.group_id=messages_v2.chat_id
          and gm.user_id=auth.uid()
          and gm.active=true
      )
    )
  )
);

grant execute on function public.leave_private_group(uuid) to authenticated;
grant execute on function public.join_private_group(uuid,text) to authenticated;
